name: intro-to-scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=20.3.0
  - automat=20.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=4.0.0
  - constantly=15.1.0
  - cryptography=3.3.1
  - cssselect=1.1.0
  - hyperlink=21.0.0
  - idna=2.10
  - incremental=17.5.0
  - intel-openmp=2020.2
  - itemadapter=0.2.0
  - itemloaders=1.0.4
  - jmespath=0.10.0
  - libiconv=1.16
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lxml=4.6.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - pandas=1.2.0
  - parsel=1.6.0
  - pip=20.3.3
  - protego=0.1.16
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pyhamcrest=2.0.2
  - pyopenssl=20.0.1
  - pysocks=1.7.1
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.5
  - pywin32=228
  - queuelib=1.5.0
  - requests=2.25.1
  - scrapy=2.4.1
  - selenium=3.141.0
  - service_identity=18.1.0
  - setuptools=49.6.0
  - six=1.15.0
  - soupsieve=2.1
  - sqlite=3.34.0
  - twisted=20.3.0
  - urllib3=1.26.2
  - vc=14.2
  - vs2015_runtime=14.28.29325
  - w3lib=1.22.0
  - wheel=0.36.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - zlib=1.2.11
  - zope.interface=5.2.0
  - pip:
    - appdirs==1.4.4
    - bs4==0.0.1
    - cachetools==4.2.0
    - fake-useragent==0.1.11
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - gspread==3.6.0
    - oauthlib==3.1.0
    - parse==1.19.0
    - pyee==8.1.0
    - pyppeteer==0.2.5
    - pyquery==1.4.3
    - requests-html==0.10.0
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - stem==1.8.0
    - tqdm==4.56.0
    - websockets==8.1
